### ISSUE TITLE
Fry adds multiple rubies to path if in Tmux with auto-switching

### ISSUE THREAD

**Issue by davidcelis** [terlar/fry#36]
This has been a tough one to try and track down, and I'm still not sure why this is happening. But if auto switching is enabled and you enter a Tmux session, the $PATH handling starts to break down...

Outside of Tmux:

```fish
~ % cat .ruby-version
2.2.0
~ % echo $PATH
/Users/david/bin /Users/david/.rubies/2.2.0/bin /usr/local/bin /usr/local/sbin /Users/david/.local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/npm/bin /usr/local/share/go/bin
~ % cd Documents/Code/davidcelis.github.io/
~Code/davidcelis.github.io master! % echo $PATH
/Users/david/Documents/Code/davidcelis.github.io/bin /Users/david/.rubies/2.0.0-p481/bin /usr/local/bin /usr/local/sbin /Users/david/.local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/npm/bin /usr/local/share/go/bin
~Code/davidcelis.github.io master! %
```

In Tmux:

```fish
~ % cat .ruby-version
2.2.0
~ % echo $PATH
/Users/david/bin /Users/david/.rubies/2.2.0/bin /usr/local/bin /usr/local/sbin /Users/david/.local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/npm/bin /usr/local/share/go/bin
~ % cd Documents/Code/davidcelis.github.io/
~Code/davidcelis.github.io master! % echo $PATH
/Users/david/Documents/Code/davidcelis.github.io/bin /Users/david/.rubies/2.0.0-p481/bin /Users/david/.rubies/2.2.0/bin /usr/local/bin /usr/local/sbin /Users/david/.local/bin /usr/local/share/npm/bin /usr/local/share/go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

So as you can see, for some reason while in Tmux, Fry doesn't replace `$fry_rubies/(fry current)/bin` with the newly found ruby version. It instead simply prepends it onto the path. The only thing I've thought to try is putting this in my config.fish

```fish
if [ -n "$TMUX" ]
  __fry_auto_switch
end
```

But simply invoking the `__fry_auto_switch` function isn't enough it seems

**Comment by davidcelis** [comment]
This might have to do with the `$fish_user_paths` variable...

**Comment by davidcelis** [comment]
Closing this, sorry. I'm almost sure this is a bug with how $fish_user_paths behaves in tmux

**Comment by terlar** [comment]
I have looked into this a bit and the problem is a combination of things. You must have something the switches directory several times so fish cannot detect the PATH changes somehow. I also had this issue because I had some code that was doing `cd some/dir` as a command to tmux when opening the session. Or also doing something funky like specifying which SHELL should be launched as command.

I found out by putting a comment here: https://github.com/terlar/fry/blob/master/share/fry/fry.fish#L46

For me it was executed 3 times with my tmux launcher. It should only be called once. After I fixed this there were no issues with the switching.

So my question is, how do you launch your TMUX session?

**Comment by davidcelis** [comment]
It looks like, for me, it's executing twice. I'm not sure what would be causing a directory switch.. I thought it might be my default-command, but removing it still causes it to be called 2 times. How were you able to debug that you had something `cd`ing when opening tmux? Or did you explicitly configure it to do that? Here's my tmux configuration:

```conf
set -g default-shell /usr/local/bin/fish
set -g default-terminal "screen-256color"
setw -g utf8 on

set -g terminal-overrides 'xterm*:smcup@:rmcup@:screen-256color'
set-option -g default-command "reattach-to-user-namespace -l fish"

# Screen
unbind ^b
set -g prefix ^a
bind a send-prefix

bind ^a last-window
bind c new-window -c "#{pane_current_path}"
bind ^c new-window -c "#{pane_current_path}"

bind A command-prompt "rename-window '%%'"

# Vim
setw -g mode-keys vi
set -g status-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind ^h select-pane -L
bind ^j select-pane -D
bind ^k select-pane -U
bind ^l select-pane -R

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind ^s split-window -v -c "#{pane_current_path}"
bind ^v split-window -h -c "#{pane_current_path}"

# Just kill the window
bind-key x kill-pane

# Set Terminal titles
set -g set-titles on
set -g set-titles-string '#h ❐ #S ● #I #W'

# Enable mouse mode
setw -g mode-mouse on
set-option -g mouse-select-pane on
set-option -g mouse-select-window on

# Theming
setw -g window-status-format " #F#I:#W#F "

setw -g window-status-current-format " #F#I:#W#F "
setw -g window-status-current-bg red
setw -g window-status-current-fg white

setw -g window-status-bg white
setw -g window-status-fg black

set -g message-fg black
set -g message-bg white
set -g message-attr bright

set -g pane-active-border-bg default
set -g pane-active-border-fg red
set -g pane-border-bg default
set -g pane-border-fg default

set -g status-left-length 100
set -g status-right-length 100

set -g status-bg black
set -g status-fg default
set -g status-attr bright
set -g status-interval 2
set -g status-justify centre

set -g status-left "#(network) #(rainbarf --bg black --width 10 --remaining)"
set -g status-right "#[fg=blue]#(forecast -m 15) #[fg=green]%H:%M %b %d %Y"
```

**Comment by davidcelis** [comment]
It looks like, even though commenting that line out makes that comment execute only once, the pathing still gets messed up. I did notice something weird though:

```fish
~ % echo $fish_user_paths
./bin /Users/david/.rubies/2.2.0/bin
~ % echo $PATH
./bin /Users/david/.rubies/2.2.0/bin /usr/local/bin /usr/local/sbin /Users/david/.local/bin /usr/local/share/npm/bin /usr/local/share/go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
~ % cd Documents/Code/davidcelis.github.io
~Code/davidcelis.github.io master % echo $fish_user_paths
./bin /Users/david/.rubies/2.0.0-p481/bin
~Code/davidcelis.github.io master % echo $PATH
/Users/david/.rubies/2.0.0-p481/bin ./bin /Users/david/.rubies/2.2.0/bin /usr/local/bin /usr/local/sbin /Users/david/.local/bin /usr/local/share/npm/bin /usr/local/share/go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

It would appear that the path from originally opening Tmux for Ruby 2.2.0 gets removed from `$fish_user_paths` after `cd`ing, but remains in $PATH.

**Comment by jordelver** [comment]
This is also happening to me with the latest release.

**Comment by jordelver** [comment]
Hmm. Can't seem to replicate this on version 1.0.5 any more.

**Comment by terlar** [comment]
Thank you for your input, I have also not been able to reproduce it since I changed my way of opening sessions and windows in `tmux`. I am convinced that the issue is that env are being set before and therefore gets lost in the tracked things. Because the `fish_user_paths` only tracks what different.

**Comment by davidcelis** [comment]
Could you share what you changed about opening sessions and windows in `tmux`?

**Comment by terlar** [comment]
Actually I think it might be due to the `default-command` which launches a new login instance of `fish`. Could you try without that to see if you get the same problem?

This is my change: https://github.com/terlar/fish-farm/commit/f427b11f09b7042491150c8e334c3f2d243c70e9

Basically just remove the launching of a new fish and use the -c to set the directory instead.

**Comment by davidcelis** [comment]
I thought that it was `reattach-to-user-namespace` but I mentioned before:

> It looks like, even though commenting that line out makes that comment execute only once, the pathing still gets messed up.

So I'm not really sure what it is. Commenting out my default command did cause auto-switch to only be called once, but pathing still messed up. I'll check out your linked commit though

**Comment by jordelver** [comment]
Did you get anywhere with this @davidcelis? I'm still having problems with fry and tmux.

**Comment by davidcelis** [comment]
unfortunately i didn't; i ended up abandoning trying to use tmux and going back to tabs.

**Comment by jordelver** [comment]
Thanks for the reply. That's a shame. I'm considering going back to ZSH because this is causing me a lot of hassle. I'm really liking Fish :(

**Comment by jordelver** [comment]
FFIW I'm using tmux 2.0, fish 2.1.2 and fry 0.1.5

**Comment by terlar** [comment]
I wonder if we can recreate this in either docker or vagrant. I am not experiencing this issue myself.

I am using: `tmux 1.9a`, `fish 2.1.2-1263-g6f438f6` and `fry 0.1.5`. If I could just get the same behaviour for me I am confident I could fix it. :/

**Comment by jordelver** [comment]
I'm not familiar with either Docker or Vagrant but I'm happy to help if you can advise?

**Comment by jordelver** [comment]
This is now working. I don't know why! Thanks for all your work :D

**Comment by terlar** [comment]
That is weird. Sorry for not being able to assist. But hard to do something when you cannot reproduce. Glad to hear it is working. Let me know if you have any other feedback.
